name: test and release

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: checkout
      uses: actions/checkout@v1
    - name: set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
    - name: lint
      run: |
        make fmt
        make lint
    - name: test
      run: |
        make test

  release:
    name: release by ghr
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    steps:
    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: checkout
      uses: actions/checkout@master
    - name: set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make release
